### PR TITLE
Ensures terminated strings are passed to crypt_ca

### PR DESCRIPTION
**Pull request by davestevens**
The call to `crypt_ca` is wrapped with a function that initialized
strings for `key` and `setting` based on the reported length rather than
using the pointer returned from `StringValuePtr`.

See: codahale/bcrypt-ruby#109.

Code example of issue: https://gist.github.com/davestevens/a9187de713a32cb005b1

### CODE REVIEW

**Comment by davestevens** [comment]
This is a result of a bug in Ruby and how Devise is calling creating a string to pass to `hash_secret`.
https://github.com/ruby/ruby/commit/622f3f14b6928ee4fe3afa96db0250eb9da32e7a

**Comment by davestevens** [comment]
This has also been resolved in Devise: plataformatec/devise#3440

**Comment by enriclluelles** [comment]
@davestevens I hit this bug today and was dumbfounded until I found your PR, using your branch until it gets merged. Thanks!

**Comment by tenderlove** [comment]
We're [using `StringValueCStr` now](https://github.com/bcrypt-ruby/bcrypt-ruby/blob/a7a868e12d80c6e0a75d81acdfdc3c4a763a622b/ext/mri/bcrypt_ext.c#L92-L93) which [NULL terminates the strings](https://github.com/ruby/ruby/blob/7be9a333cabd97a17a2926b15f756f2ef9e57243/doc/extension.rdoc?plain=1#L121-L124), so I don't think this PR is necessary.

Thank you!

**Pull request closed without merging**
